server:
  port: 8080
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

spring:
  cache:
    type: redis
    redis:
      time-to-live: 300s
  security:
    user:
      name: root
      password: root
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: "sa"
    url: jdbc:sqlserver://localhost:1433;database=MyBlog;encrypt=false;trustServerCertificate=true;sendStringParametersAsUnicode=true;
    hikari: # 配置连接池
      maximum-pool-size: 10
      idle-timeout: 30000
    password: "14152519487@Cen"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      connect-timeout: 3600000
      database: 0
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  sql:
    init:
      encoding: utf-8
  

jwt:
  secret: 8J6bZzqkRtA7X9LvMwYhN2PpQeFjHnKsDcV4BfGxTqWu3yJ5rCt0Oa1iEoUl+/M=
  expiration: 3600

pathMap:
  uploadDir: C:/uploads/images
  accessPath: /img/**
# 开启 MapStruct 调试模式
#
#  mapstruct.suppress.generator.timestamp=true
#  mapstruct.suppress.generator.version.comment=true
#  mapstruct.default.componentModel=spring
