server:
  port: 8080
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

spring:
  cache:
    type: redis
  security:
    user:
      name: root
      password: root
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: "sa"
    url: jdbc:sqlserver://localhost:1433;database=MyBlog;encrypt=false;trustServerCertificate=true;
    hikari: # 配置连接池
      maximum-pool-size: 10
      idle-timeout: 30000
    password: "14152519487@Cen"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 3600000

jwt:
  secret: 8J6bZzqkRtA7X9LvMwYhN2PpQeFjHnKsDcV4BfGxTqWu3yJ5rCt0Oa1iEoUl+/M=
  expiration: 3600

pathMap:
  uploadDir: C:upload/image
  accessPath: /img