/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./components/ArticleCard.vue')['default']
    ArticleDetail: typeof import('./components/ArticleDetail.vue')['default']
    ArticleHome: typeof import('./components/ArticleHome.vue')['default']
    Avatar: typeof import('./components/Avatar.vue')['default']
    Comment: typeof import('./components/Comment.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tests: typeof import('./components/Tests.vue')['default']
  }
}
